import "../../src/export/html/index";

interface V8HeapSnapshot {
	snapshot: {
		meta: {
			node_fields: string[];
			node_types: Array<string | string[]>;
		};
	};
	nodes: number[];
	strings: string[];
}

interface AssetClass {
	name: string;
	prefix: string;
	minSelfSize: number;
}

const assetClasses: AssetClass[] = [
	{
		name: "template.html",
		prefix: '<!DOCTYPE html>\n<html lang="en">',
		minSelfSize: 4 * 1024,
	},
	{
		name: "template.css",
		prefix: "    /* Export page chrome",
		minSelfSize: 48 * 1024,
	},
	{
		name: "template.js",
		prefix: "    (function() {\n      'use strict';",
		minSelfSize: 96 * 1024,
	},
	{
		name: "tool-views.generated.js",
		prefix: "// Auto-generated by packages/collab-web/scripts/build-tool-views.ts - DO NOT EDIT",
		minSelfSize: 512 * 1024,
	},
];

Bun.gc(true);
const heap = JSON.parse(Bun.generateHeapSnapshot("v8")) as V8HeapSnapshot;
const { node_fields: nodeFields, node_types: nodeTypes } = heap.snapshot.meta;
const typeOffset = nodeFields.indexOf("type");
const nameOffset = nodeFields.indexOf("name");
const sizeOffset = nodeFields.indexOf("self_size");
const typeNames = nodeTypes[typeOffset];
if (typeOffset < 0 || nameOffset < 0 || sizeOffset < 0 || !Array.isArray(typeNames)) {
	throw new Error("Unexpected V8 heap snapshot schema");
}

const retainedAssets: Array<{ name: string; selfSize: number }> = [];
for (let nodeOffset = 0; nodeOffset < heap.nodes.length; nodeOffset += nodeFields.length) {
	if (typeNames[heap.nodes[nodeOffset + typeOffset]!] !== "string") continue;
	const value = heap.strings[heap.nodes[nodeOffset + nameOffset]!];
	const selfSize = heap.nodes[nodeOffset + sizeOffset]!;
	if (value === undefined) continue;
	for (const asset of assetClasses) {
		if (selfSize >= asset.minSelfSize && value.startsWith(asset.prefix)) {
			retainedAssets.push({ name: asset.name, selfSize });
			break;
		}
	}
}
retainedAssets.sort((left, right) => left.name.localeCompare(right.name));

process.stdout.write(JSON.stringify({ retainedAssetStrings: retainedAssets.length, retainedAssets }));
